//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.03 at 09:46:17 AM CEST 
//


package de.wbstraining.lotto.testdatengenerierung;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the wbs.lotto.testdatengenerierung package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wbs.lotto.testdatengenerierung
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Testdatengenerator }
     * 
     */
    public Testdatengenerator createTestdatengenerator() {
        return new Testdatengenerator();
    }

    /**
     * Create an instance of {@link CZiehung }
     * 
     */
    public CZiehung createCZiehung() {
        return new CZiehung();
    }

    /**
     * Create an instance of {@link AnzahlSuper6ProGkl }
     * 
     */
    public AnzahlSuper6ProGkl createAnzahlSuper6ProGkl() {
        return new AnzahlSuper6ProGkl();
    }

    /**
     * Create an instance of {@link AnzahlSpiel77ProGkl }
     * 
     */
    public AnzahlSpiel77ProGkl createAnzahlSpiel77ProGkl() {
        return new AnzahlSpiel77ProGkl();
    }

    /**
     * Create an instance of {@link Anzahl6Aus49ProGkl }
     * 
     */
    public Anzahl6Aus49ProGkl createAnzahl6Aus49ProGkl() {
        return new Anzahl6Aus49ProGkl();
    }

}
