//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.03 at 09:46:17 AM CEST 
//


package de.wbstraining.lotto.testdatengenerierung;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="cZiehung" type="{http://testdatengenerierung.lotto.wbs/lotto}cZiehung"/>
 *       &lt;/sequence>
 *       &lt;attribute name="datumErsteZiehung" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="belegnummernStart" use="required" type="{http://testdatengenerierung.lotto.wbs/lotto}belegNummer" />
 *       &lt;attribute name="txBlocksize" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cZiehung"
})
@XmlRootElement(name = "testdatengenerator")
public class Testdatengenerator {

    @XmlElement(required = true)
    protected List<CZiehung> cZiehung;
    @XmlAttribute(name = "datumErsteZiehung", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumErsteZiehung;
    @XmlAttribute(name = "belegnummernStart", required = true)
    protected long belegnummernStart;
    @XmlAttribute(name = "txBlocksize", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected int txBlocksize;

    /**
     * Gets the value of the cZiehung property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cZiehung property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCZiehung().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CZiehung }
     * 
     * 
     */
    public List<CZiehung> getCZiehung() {
        if (cZiehung == null) {
            cZiehung = new ArrayList<CZiehung>();
        }
        return this.cZiehung;
    }

    /**
     * Gets the value of the datumErsteZiehung property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumErsteZiehung() {
        return datumErsteZiehung;
    }

    /**
     * Sets the value of the datumErsteZiehung property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumErsteZiehung(XMLGregorianCalendar value) {
        this.datumErsteZiehung = value;
    }

    /**
     * Gets the value of the belegnummernStart property.
     * 
     */
    public long getBelegnummernStart() {
        return belegnummernStart;
    }

    /**
     * Sets the value of the belegnummernStart property.
     * 
     */
    public void setBelegnummernStart(long value) {
        this.belegnummernStart = value;
    }

    /**
     * Gets the value of the txBlocksize property.
     * 
     */
    public int getTxBlocksize() {
        return txBlocksize;
    }

    /**
     * Sets the value of the txBlocksize property.
     * 
     */
    public void setTxBlocksize(int value) {
        this.txBlocksize = value;
    }

}
